language: node_js
node_js:
  - "7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs npm python3 python3-pip
  - pip3 install --user schul_cloud_search_tests


install:
  - npm install

script:
  - npm test

